/**
 * Make module catalog — same Public API surface as Zapier CATALOG / n8n operations.
 * Paths are relative to /api/v1/public (set on app base).
 */
const { ASSESS_WEBHOOK_EVENTS } = require("./events");

const EVENT_OPTIONS = ASSESS_WEBHOOK_EVENTS.map((e) => ({ label: e.label, value: e.value }));

const PROVIDER_OPTIONS = [
  { label: "Greenhouse", value: "greenhouse" },
  { label: "Lever", value: "lever" },
  { label: "Ashby", value: "ashby" },
  { label: "Workday", value: "workday" },
  { label: "BambooHR", value: "bamboohr" },
];

function camelModule(resource, operation) {
  return resource + operation.charAt(0).toUpperCase() + operation.slice(1);
}

/** @typedef {{ name: string, type?: string, label: string, required?: boolean, help?: string, default?: any, options?: {label:string,value:string}[], nested?: object[] }} MakeParam */

/** @type {Array<{
 *  resource: string,
 *  operation: string,
 *  moduleType: 'action'|'search',
 *  label: string,
 *  description: string,
 *  method: string,
 *  path: string,
 *  paginated?: boolean,
 *  params?: MakeParam[],
 *  qs?: Record<string, string>,
 *  body?: Record<string, string>|null,
 *  sample?: object,
 * }>} */
const CATALOG = [
  // —— Assessments ——
  {
    resource: "assessment",
    operation: "list",
    moduleType: "search",
    label: "List Assessments",
    description: "List assessments in the organisation.",
    method: "GET",
    path: "/assessments/",
    paginated: true,
    params: [
      { name: "cursor", type: "text", label: "Cursor", help: "Pagination cursor" },
      { name: "page_size", type: "number", label: "Page Size", help: "Default 20, max 100", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { slug: "senior-backend-screen", title: "Senior Backend", status: "active" },
  },
  {
    resource: "assessment",
    operation: "get",
    moduleType: "action",
    label: "Get Assessment",
    description: "Get one assessment by slug.",
    method: "GET",
    path: "/assessments/{{parameters.slug}}/",
    params: [{ name: "slug", type: "text", label: "Assessment Slug", required: true }],
    sample: { slug: "senior-backend-screen", title: "Senior Backend" },
  },
  {
    resource: "assessment",
    operation: "create",
    moduleType: "action",
    label: "Create Assessment",
    description: "Create an assessment.",
    method: "POST",
    path: "/assessments/create/",
    params: [
      { name: "title", type: "text", label: "Title", required: true },
      { name: "description", type: "text", label: "Description" },
      { name: "time_limit_minutes", type: "number", label: "Time Limit (Minutes)", default: 60 },
      { name: "passing_score", type: "number", label: "Passing Score", default: 70 },
      { name: "team_id", type: "text", label: "Squad ID" },
    ],

    sample: { slug: "senior-backend-screen", title: "Senior Backend" },
  },
  {
    resource: "assessment",
    operation: "update",
    moduleType: "action",
    label: "Update Assessment",
    description: "Update an assessment.",
    method: "PATCH",
    path: "/assessments/{{parameters.slug}}/update/",
    params: [
      { name: "slug", type: "text", label: "Assessment Slug", required: true },
      { name: "title", type: "text", label: "Title" },
      { name: "description", type: "text", label: "Description" },
      {
        name: "status",
        type: "select",
        label: "Status",
        options: [
          { label: "Draft", value: "draft" },
          { label: "Active", value: "active" },
          { label: "Archived", value: "archived" },
        ],
      },
    ],

    sample: { slug: "senior-backend-screen", status: "active" },
  },
  {
    resource: "assessment",
    operation: "duplicate",
    moduleType: "action",
    label: "Duplicate Assessment",
    description: "Duplicate an assessment.",
    method: "POST",
    path: "/assessments/{{parameters.slug}}/duplicate/",
    params: [{ name: "slug", type: "text", label: "Assessment Slug", required: true }],
    sample: { slug: "senior-backend-screen-copy" },
  },
  {
    resource: "assessment",
    operation: "listResults",
    moduleType: "search",
    label: "List Assessment Results",
    description: "List results for an assessment.",
    method: "GET",
    path: "/assessments/{{parameters.slug}}/results/",
    paginated: true,
    params: [
      { name: "slug", type: "text", label: "Assessment Slug", required: true },
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { invite_token: "inv_abc", overall_score: 82, passed: true },
  },
  {
    resource: "assessment",
    operation: "listCases",
    moduleType: "search",
    label: "List Assessment Cases",
    description: "List cases attached to an assessment.",
    method: "GET",
    path: "/assessments/{{parameters.slug}}/cases/",
    paginated: true,
    params: [
      { name: "slug", type: "text", label: "Assessment Slug", required: true },
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { id: "case-uuid", title: "SQL joins" },
  },
  {
    resource: "assessment",
    operation: "attachCases",
    moduleType: "action",
    label: "Attach Cases",
    description: "Attach cases to an assessment.",
    method: "POST",
    path: "/assessments/{{parameters.slug}}/cases/attach/",
    listFields: ["case_ids"],
    params: [
      { name: "slug", type: "select", label: "Assessment", required: true, rpc: "listAssessmentsRpc" },
      {
        name: "case_ids",
        type: "text",
        label: "Case IDs",
        required: true,
        help: "Comma-separated UUIDs, or a JSON array like [\"uuid\",…]",
      },
    ],
    sample: { ok: true },
  },
  {
    resource: "assessment",
    operation: "replaceCases",
    moduleType: "action",
    label: "Replace Cases",
    description: "Replace all cases on an assessment.",
    method: "PUT",
    path: "/assessments/{{parameters.slug}}/cases/replace/",
    listFields: ["case_ids"],
    params: [
      { name: "slug", type: "select", label: "Assessment", required: true, rpc: "listAssessmentsRpc" },
      {
        name: "case_ids",
        type: "text",
        label: "Case IDs",
        required: true,
        help: "Comma-separated UUIDs, or a JSON array like [\"uuid\",…]",
      },
    ],
    sample: { ok: true },
  },
  {
    resource: "assessment",
    operation: "removeCase",
    moduleType: "action",
    label: "Remove Case",
    description: "Remove one case from an assessment.",
    method: "DELETE",
    path: "/assessments/{{parameters.slug}}/cases/remove/",
    params: [
      { name: "slug", type: "text", label: "Assessment Slug", required: true },
      { name: "case_id", type: "text", label: "Case ID", required: true },
    ],

    sample: { ok: true },
  },

  // —— Cases ——
  {
    resource: "case",
    operation: "list",
    moduleType: "search",
    label: "List Org Cases",
    description: "List organisation cases.",
    method: "GET",
    path: "/cases/",
    paginated: true,
    params: [
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { id: "case-uuid", title: "MCQ" },
  },
  {
    resource: "case",
    operation: "listPlatform",
    moduleType: "search",
    label: "List Platform Cases",
    description: "List Praxicraft platform library cases.",
    method: "GET",
    path: "/platform-cases/",
    paginated: true,
    params: [
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { id: "plat-uuid", title: "Python ETL" },
  },
  {
    resource: "case",
    operation: "create",
    moduleType: "action",
    label: "Create Case",
    description: "Create an organisation case.",
    method: "POST",
    path: "/cases/create/",
    jsonFields: ["options_json"],
    jsonFieldMap: { options_json: "options" },
    params: [
      { name: "title", type: "text", label: "Title", required: true },
      {
        name: "case_type",
        type: "select",
        label: "Case Type",
        default: "mcq",
        options: [
          { label: "MCQ", value: "mcq" },
          { label: "Coding", value: "coding" },
          { label: "Text", value: "text" },
        ],
      },
      {
        name: "difficulty",
        type: "select",
        label: "Difficulty",
        default: "medium",
        options: [
          { label: "Easy", value: "easy" },
          { label: "Medium", value: "medium" },
          { label: "Hard", value: "hard" },
        ],
      },
      { name: "points", type: "number", label: "Points", default: 10 },
      { name: "question", type: "text", label: "Question" },
      { name: "description", type: "text", label: "Description" },
      { name: "tags", type: "text", label: "Tags" },
      {
        name: "options_json",
        type: "text",
        label: "MCQ Options JSON",
        help: "Optional JSON array/object for MCQ options",
      },
    ],
    sample: { id: "case-uuid", title: "MCQ" },
  },
  {
    resource: "case",
    operation: "get",
    moduleType: "action",
    label: "Get Case",
    description: "Get an organisation case.",
    method: "GET",
    path: "/cases/{{parameters.id}}/",
    params: [{ name: "id", type: "text", label: "Case ID", required: true }],
    sample: { id: "case-uuid", title: "MCQ" },
  },
  {
    resource: "case",
    operation: "update",
    moduleType: "action",
    label: "Update Case",
    description: "Update an organisation case.",
    method: "PATCH",
    path: "/cases/{{parameters.id}}/",
    params: [
      { name: "id", type: "text", label: "Case ID", required: true },
      { name: "title", type: "text", label: "Title" },
      { name: "question", type: "text", label: "Question" },
      { name: "description", type: "text", label: "Description" },
    ],

    sample: { id: "case-uuid" },
  },
  {
    resource: "case",
    operation: "delete",
    moduleType: "action",
    label: "Delete Case",
    description: "Delete an organisation case.",
    method: "DELETE",
    path: "/cases/{{parameters.id}}/",
    params: [{ name: "id", type: "text", label: "Case ID", required: true }],
    sample: { ok: true },
  },

  // —— Invitations ——
  {
    resource: "invitation",
    operation: "list",
    moduleType: "search",
    label: "List Invitations",
    description: "List invitations.",
    method: "GET",
    path: "/invites/",
    paginated: true,
    params: [
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { invite_token: "inv_abc", email: "ada@example.com", status: "pending" },
  },
  {
    resource: "invitation",
    operation: "invite",
    moduleType: "action",
    label: "Invite Candidate",
    description: "Invite a candidate to an active assessment.",
    method: "POST",
    path: "/assessments/{{parameters.slug}}/invites/",
    params: [
      { name: "slug", type: "select", label: "Assessment", required: true, rpc: "listAssessmentsRpc" },
      { name: "email", type: "email", label: "Email", required: true },
      { name: "name", type: "text", label: "Name" },
      { name: "send_email", type: "boolean", label: "Send Email", default: false },
      { name: "expires_days", type: "number", label: "Expires (Days)", default: 7 },
      {
        name: "external_id",
        type: "text",
        label: "External ID",
        help: "ATS candidate id. Retries with the same id return the existing invite.",
      },
    ],

    sample: {
      invite_token: "inv_abc",
      invite_url: "https://assess.praxicraft.com/take/inv_abc",
      email: "ada@example.com",
    },
  },
  {
    resource: "invitation",
    operation: "bulkInvite",
    moduleType: "action",
    label: "Bulk Invite Candidates",
    description: "Invite many candidates to an assessment.",
    method: "POST",
    path: "/assessments/{{parameters.slug}}/invites/bulk/",
    jsonFields: ["candidates"],
    params: [
      { name: "slug", type: "select", label: "Assessment", required: true, rpc: "listAssessmentsRpc" },
      {
        name: "candidates",
        type: "text",
        label: "Candidates JSON",
        required: true,
        help: 'Required JSON array: [{"email":"a@b.com","name":"Ada"}]',
      },
      { name: "send_email", type: "boolean", label: "Send Email", default: false },
      { name: "expires_days", type: "number", label: "Expires (Days)", default: 7 },
    ],

    sample: { invited: [], skipped: [] },
  },
  {
    resource: "invitation",
    operation: "get",
    moduleType: "action",
    label: "Get Invitation",
    description: "Get an invitation by invite_token.",
    method: "GET",
    path: "/invites/{{parameters.token}}/",
    params: [{ name: "token", type: "text", label: "Invite Token", required: true }],
    sample: { invite_token: "inv_abc", status: "pending" },
  },
  {
    resource: "invitation",
    operation: "getResult",
    moduleType: "action",
    label: "Get Invitation Result",
    description: "Get the scored result for an invitation.",
    method: "GET",
    path: "/invites/{{parameters.token}}/result/",
    params: [{ name: "token", type: "text", label: "Invite Token", required: true }],
    sample: { invite_token: "inv_abc", overall_score: 82, passed: true },
  },
  {
    resource: "invitation",
    operation: "remind",
    moduleType: "action",
    label: "Remind Candidate",
    description: "Send an invitation reminder.",
    method: "POST",
    path: "/invites/{{parameters.token}}/remind/",
    params: [{ name: "token", type: "text", label: "Invite Token", required: true }],
    sample: { ok: true },
  },
  {
    resource: "invitation",
    operation: "cancel",
    moduleType: "action",
    label: "Cancel Invitation",
    description: "Cancel a pending invitation.",
    method: "DELETE",
    path: "/invites/{{parameters.token}}/",
    params: [{ name: "token", type: "text", label: "Invite Token", required: true }],
    sample: { ok: true },
  },

  // —— Pipelines ——
  {
    resource: "pipeline",
    operation: "list",
    moduleType: "search",
    label: "List Pipelines",
    description: "List pipelines.",
    method: "GET",
    path: "/pipelines/",
    paginated: true,
    params: [
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { slug: "grad-2025", name: "Grad 2025" },
  },
  {
    resource: "pipeline",
    operation: "get",
    moduleType: "action",
    label: "Get Pipeline",
    description: "Get a pipeline by slug.",
    method: "GET",
    path: "/pipelines/{{parameters.slug}}/",
    params: [{ name: "slug", type: "select", label: "Pipeline", required: true, rpc: "listPipelinesRpc" }],
    sample: { slug: "grad-2025" },
  },
  {
    resource: "pipeline",
    operation: "enroll",
    moduleType: "action",
    label: "Enroll Candidate",
    description: "Enroll a candidate in a pipeline.",
    method: "POST",
    path: "/pipelines/{{parameters.slug}}/enroll/",
    params: [
      { name: "slug", type: "select", label: "Pipeline", required: true, rpc: "listPipelinesRpc" },
      { name: "email", type: "email", label: "Email", required: true },
      { name: "name", type: "text", label: "Name" },
      { name: "send_email", type: "boolean", label: "Send Email", default: false },
    ],

    sample: { id: "enr_abc", email: "ada@example.com" },
  },
  {
    resource: "pipeline",
    operation: "bulkEnroll",
    moduleType: "action",
    label: "Bulk Enroll Candidates",
    description: "Enroll many candidates in a pipeline.",
    method: "POST",
    path: "/pipelines/{{parameters.slug}}/enroll/bulk/",
    jsonFields: ["candidates"],
    params: [
      { name: "slug", type: "select", label: "Pipeline", required: true, rpc: "listPipelinesRpc" },
      {
        name: "candidates",
        type: "text",
        label: "Candidates JSON",
        required: true,
        help: 'Required JSON array: [{"email":"a@b.com","name":"Ada"}]',
      },
      { name: "send_email", type: "boolean", label: "Send Email", default: false },
    ],
    sample: { enrolled: [], skipped: [] },
  },
  {
    resource: "pipeline",
    operation: "listEnrollments",
    moduleType: "search",
    label: "List Enrollments",
    description: "List pipeline enrollments.",
    method: "GET",
    path: "/pipelines/{{parameters.slug}}/enrollments/",
    paginated: true,
    params: [
      { name: "slug", type: "text", label: "Pipeline Slug", required: true },
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { id: "enr_abc", status: "active" },
  },
  {
    resource: "pipeline",
    operation: "getEnrollment",
    moduleType: "action",
    label: "Get Enrollment",
    description: "Get one enrollment.",
    method: "GET",
    path: "/pipelines/enrollments/{{parameters.id}}/",
    params: [{ name: "id", type: "text", label: "Enrollment ID", required: true }],
    sample: { id: "enr_abc" },
  },
  {
    resource: "pipeline",
    operation: "reject",
    moduleType: "action",
    label: "Reject Enrollment",
    description: "Reject a pipeline enrollment.",
    method: "POST",
    path: "/pipelines/enrollments/{{parameters.id}}/reject/",
    params: [
      { name: "id", type: "text", label: "Enrollment ID", required: true },
      { name: "reason", type: "text", label: "Reason" },
    ],

    sample: { id: "enr_abc", status: "rejected" },
  },
  {
    resource: "pipeline",
    operation: "hold",
    moduleType: "action",
    label: "Hold Enrollment",
    description: "Hold a pipeline enrollment.",
    method: "POST",
    path: "/pipelines/enrollments/{{parameters.id}}/hold/",
    params: [{ name: "id", type: "text", label: "Enrollment ID", required: true }],
    sample: { id: "enr_abc", status: "held" },
  },
  {
    resource: "pipeline",
    operation: "unhold",
    moduleType: "action",
    label: "Unhold Enrollment",
    description: "Unhold a pipeline enrollment.",
    method: "POST",
    path: "/pipelines/enrollments/{{parameters.id}}/unhold/",
    params: [{ name: "id", type: "text", label: "Enrollment ID", required: true }],
    sample: { id: "enr_abc", status: "active" },
  },

  // —— Webhooks ——
  {
    resource: "webhook",
    operation: "list",
    moduleType: "search",
    label: "List Webhooks",
    description: "List webhook destinations.",
    method: "GET",
    path: "/webhooks/",
    paginated: true,
    params: [
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { id: "wh_abc", url: "https://example.com/hook" },
  },
  {
    resource: "webhook",
    operation: "create",
    moduleType: "action",
    label: "Create Webhook",
    description: "Register a webhook destination.",
    method: "POST",
    path: "/webhooks/create/",
    listFields: ["events"],
    params: [
      { name: "url", type: "url", label: "URL", required: true },
      {
        name: "events",
        type: "text",
        label: "Events",
        required: true,
        help: "Comma-separated event names, or a JSON array of event strings",
      },
      { name: "name", type: "text", label: "Name" },
    ],
    sample: { id: "wh_abc", secret_key: "whsec_xxx" },
  },
  {
    resource: "webhook",
    operation: "get",
    moduleType: "action",
    label: "Get Webhook",
    description: "Get a webhook destination.",
    method: "GET",
    path: "/webhooks/{{parameters.id}}/",
    params: [{ name: "id", type: "text", label: "Webhook ID", required: true }],
    sample: { id: "wh_abc" },
  },
  {
    resource: "webhook",
    operation: "update",
    moduleType: "action",
    label: "Update Webhook",
    description: "Update a webhook destination.",
    method: "PATCH",
    path: "/webhooks/{{parameters.id}}/",
    listFields: ["events"],
    params: [
      { name: "id", type: "text", label: "Webhook ID", required: true },
      { name: "url", type: "url", label: "URL" },
      {
        name: "events",
        type: "text",
        label: "Events",
        help: "Comma-separated event names, or a JSON array",
      },
      { name: "is_active", type: "boolean", label: "Is Active" },
      { name: "name", type: "text", label: "Name" },
    ],
    sample: { id: "wh_abc" },
  },
  {
    resource: "webhook",
    operation: "delete",
    moduleType: "action",
    label: "Delete Webhook",
    description: "Delete a webhook destination.",
    method: "DELETE",
    path: "/webhooks/{{parameters.id}}/",
    bodyMode: "none",
    params: [{ name: "id", type: "text", label: "Webhook ID", required: true }],
    sample: { ok: true },
  },
  {
    resource: "webhook",
    operation: "listDeliveries",
    moduleType: "search",
    label: "List Webhook Deliveries",
    description: "List recent deliveries for a webhook.",
    method: "GET",
    path: "/webhooks/{{parameters.id}}/deliveries/",
    paginated: true,
    params: [
      { name: "id", type: "text", label: "Webhook ID", required: true },
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { id: "del_abc", status: "delivered", event_type: "candidate.passed" },
  },
  {
    resource: "webhook",
    operation: "test",
    moduleType: "action",
    label: "Test Webhook",
    description: "Send a webhook.test ping.",
    method: "POST",
    path: "/webhooks/{{parameters.id}}/test/",
    params: [{ name: "id", type: "text", label: "Webhook ID", required: true }],
    sample: { ok: true },
  },

  // —— Organisation ——
  {
    resource: "organisation",
    operation: "get",
    moduleType: "action",
    label: "Get Organisation",
    description: "Get organisation profile and invite quota.",
    method: "GET",
    path: "/org/",
    params: [],
    sample: { name: "Acme", plan: "starter", invites_remaining: 40 },
  },
  {
    resource: "organisation",
    operation: "stats",
    moduleType: "action",
    label: "Get Organisation Stats",
    description: "Get organisation stats.",
    method: "GET",
    path: "/org/stats/",
    params: [],
    sample: { assessments: 3 },
  },
  {
    resource: "organisation",
    operation: "listTeam",
    moduleType: "search",
    label: "List Team Members",
    description: "List organisation team members.",
    method: "GET",
    path: "/org/team/",
    paginated: true,
    params: [
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { email: "owner@acme.com", role: "owner" },
  },
  {
    resource: "organisation",
    operation: "listSquads",
    moduleType: "search",
    label: "List Squads",
    description: "List hiring squads.",
    method: "GET",
    path: "/org/squads/",
    paginated: true,
    params: [
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { id: "squad-uuid", name: "Growth" },
  },
  {
    resource: "organisation",
    operation: "getSquad",
    moduleType: "action",
    label: "Get Squad",
    description: "Get a hiring squad.",
    method: "GET",
    path: "/org/squads/{{parameters.id}}/",
    params: [{ name: "id", type: "text", label: "Squad ID", required: true }],
    sample: { id: "squad-uuid" },
  },
  {
    resource: "organisation",
    operation: "listSquadMembers",
    moduleType: "search",
    label: "List Squad Members",
    description: "List members of a squad.",
    method: "GET",
    path: "/org/squads/{{parameters.id}}/members/",
    paginated: true,
    params: [
      { name: "id", type: "text", label: "Squad ID", required: true },
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { email: "recruiter@acme.com" },
  },
  {
    resource: "organisation",
    operation: "auditLog",
    moduleType: "search",
    label: "List Audit Log",
    description: "List organisation audit log rows.",
    method: "GET",
    path: "/org/audit-log/",
    paginated: true,
    params: [
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { action: "invitation.created" },
  },

  // —— Interviews ——
  {
    resource: "interview",
    operation: "list",
    moduleType: "search",
    label: "List Interviews",
    description: "List interview rooms.",
    method: "GET",
    path: "/interviews/",
    paginated: true,
    params: [
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { id: "room-uuid", title: "AI Screen" },
  },
  {
    resource: "interview",
    operation: "create",
    moduleType: "action",
    label: "Create Interview",
    description: "Create an interview room and optionally email the candidate.",
    method: "POST",
    path: "/interviews/create/",
    params: [
      { name: "candidate_email", type: "email", label: "Candidate Email", required: true },
      { name: "candidate_name", type: "text", label: "Candidate Name" },
      { name: "title", type: "text", label: "Title", default: "AI Screening Interview" },
      {
        name: "interviewer_mode",
        type: "select",
        label: "Interviewer Mode",
        default: "ai_only",
        options: [
          { label: "AI Only", value: "ai_only" },
          { label: "Human Only", value: "human_only" },
          { label: "Hybrid", value: "hybrid" },
        ],
      },
      { name: "interview_type", type: "text", label: "Interview Type", default: "mixed" },
      { name: "job_description", type: "text", label: "Job Description" },
      { name: "resume_text", type: "text", label: "Resume Text" },
      { name: "send_invite", type: "boolean", label: "Send Invite", default: true },
      { name: "scheduled_at", type: "date", label: "Scheduled At" },
      { name: "coding_case_ids", type: "text", label: "Coding Case IDs", help: "Comma-separated UUIDs or JSON array" },
      { name: "org_case_ids", type: "text", label: "Org Case IDs", help: "Comma-separated UUIDs or JSON array" },
    ],
    listFields: ["coding_case_ids", "org_case_ids"],
    sample: { id: "room-uuid", candidate_email: "ada@example.com" },
  },
  {
    resource: "interview",
    operation: "bulkCreate",
    moduleType: "action",
    label: "Bulk Create Interviews",
    description: "Create interview rooms for many candidates.",
    method: "POST",
    path: "/interviews/bulk/",
    jsonFields: ["candidates"],
    params: [
      {
        name: "candidates",
        type: "text",
        label: "Candidates JSON",
        required: true,
        help: 'Required JSON array: [{"email":"a@b.com","name":"Ada"}]',
      },
      { name: "title", type: "text", label: "Title" },
      { name: "interviewer_mode", type: "text", label: "Interviewer Mode", default: "ai_only" },
      { name: "job_description", type: "text", label: "Job Description" },
      { name: "resume_text", type: "text", label: "Resume Text" },
      { name: "send_invite", type: "boolean", label: "Send Invite", default: true },
    ],
    sample: { created: [] },
  },
  {
    resource: "interview",
    operation: "get",
    moduleType: "action",
    label: "Get Interview",
    description: "Get an interview room.",
    method: "GET",
    path: "/interviews/{{parameters.id}}/",
    params: [{ name: "id", type: "text", label: "Interview ID", required: true }],
    sample: { id: "room-uuid" },
  },
  {
    resource: "interview",
    operation: "cancel",
    moduleType: "action",
    label: "Cancel Interview",
    description: "Cancel an interview room.",
    method: "POST",
    path: "/interviews/{{parameters.id}}/cancel/",
    params: [{ name: "id", type: "text", label: "Interview ID", required: true }],
    sample: { id: "room-uuid", status: "cancelled" },
  },
  {
    resource: "interview",
    operation: "reschedule",
    moduleType: "action",
    label: "Reschedule Interview",
    description: "Reschedule an interview.",
    method: "POST",
    path: "/interviews/{{parameters.id}}/reschedule/",
    params: [
      { name: "id", type: "text", label: "Interview ID", required: true },
      { name: "scheduled_at", type: "date", label: "Scheduled At", required: true },
    ],

    sample: { id: "room-uuid" },
  },
  {
    resource: "interview",
    operation: "analysis",
    moduleType: "action",
    label: "Get Interview Analysis",
    description: "Get interview analysis.",
    method: "GET",
    path: "/interviews/{{parameters.id}}/analysis/",
    params: [{ name: "id", type: "text", label: "Interview ID", required: true }],
    sample: { score: 4, hire_recommendation: "yes" },
  },
  {
    resource: "interview",
    operation: "replay",
    moduleType: "action",
    label: "Get Interview Replay",
    description: "Get interview replay metadata.",
    method: "GET",
    path: "/interviews/{{parameters.id}}/replay/",
    params: [{ name: "id", type: "text", label: "Interview ID", required: true }],
    sample: { recording_url: "https://..." },
  },
  {
    resource: "interview",
    operation: "share",
    moduleType: "action",
    label: "Share Interview",
    description: "Create a share link for an interview report.",
    method: "POST",
    path: "/interviews/{{parameters.id}}/share/",
    params: [
      { name: "id", type: "text", label: "Interview ID", required: true },
      { name: "expires_days", type: "number", label: "Expires (Days)", default: 14 },
    ],

    sample: { share_url: "https://assess.praxicraft.com/interview/share/..." },
  },
  {
    resource: "interview",
    operation: "analytics",
    moduleType: "action",
    label: "Get Interview Analytics",
    description: "Get organisation interview analytics.",
    method: "GET",
    path: "/interviews/analytics/",
    params: [],
    sample: { completed: 12 },
  },
  {
    resource: "interview",
    operation: "listTemplates",
    moduleType: "search",
    label: "List Interview Templates",
    description: "List interview templates.",
    method: "GET",
    path: "/interviews/templates/",
    paginated: true,
    params: [
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { id: "tpl-uuid", name: "Backend screen" },
  },
  {
    resource: "interview",
    operation: "createTemplate",
    moduleType: "action",
    label: "Create Interview Template",
    description: "Create an interview template.",
    method: "POST",
    path: "/interviews/templates/create/",
    jsonFields: ["config_json"],
    jsonFieldMap: { config_json: "config" },
    params: [
      { name: "name", type: "text", label: "Name", required: true },
      { name: "config_json", type: "text", label: "Config JSON", help: "Optional JSON object" },
    ],
    sample: { id: "tpl-uuid", name: "Backend screen" },
  },
  {
    resource: "interview",
    operation: "updateTemplate",
    moduleType: "action",
    label: "Update Interview Template",
    description: "Update an interview template.",
    method: "PATCH",
    path: "/interviews/templates/{{parameters.id}}/update/",
    jsonFields: ["config_json"],
    jsonFieldMap: { config_json: "config" },
    params: [
      { name: "id", type: "text", label: "Template ID", required: true },
      { name: "name", type: "text", label: "Name" },
      { name: "config_json", type: "text", label: "Config JSON" },
    ],
    sample: { id: "tpl-uuid" },
  },
  {
    resource: "interview",
    operation: "deleteTemplate",
    moduleType: "action",
    label: "Delete Interview Template",
    description: "Delete an interview template.",
    method: "DELETE",
    path: "/interviews/templates/{{parameters.id}}/delete/",
    params: [{ name: "id", type: "text", label: "Template ID", required: true }],
    sample: { ok: true },
  },
  {
    resource: "interview",
    operation: "listOrgCases",
    moduleType: "search",
    label: "List Interview Org Cases",
    description: "List org cases available for interviews.",
    method: "GET",
    path: "/interviews/org-cases/",
    paginated: true,
    params: [
      { name: "cursor", type: "text", label: "Cursor" },
      { name: "page_size", type: "number", label: "Page Size", default: 20 },
    ],
    qs: { cursor: "{{parameters.cursor}}", page_size: "{{parameters.page_size}}" },
    sample: { id: "case-uuid" },
  },

  // —— Integrations ——
  {
    resource: "integration",
    operation: "list",
    moduleType: "action",
    label: "List Integrations",
    description: "List ATS integration status (no secrets).",
    method: "GET",
    path: "/integrations/",
    params: [],
    sample: { integrations: [] },
  },
  {
    resource: "integration",
    operation: "connect",
    moduleType: "action",
    label: "Get Integration Connect URL",
    description: "Get the dashboard connect URL for an ATS provider.",
    method: "GET",
    path: "/integrations/{{parameters.provider}}/connect/",
    params: [
      { name: "provider", type: "select", label: "ATS Provider", required: true, options: PROVIDER_OPTIONS },
    ],
    sample: {
      connect_url: "https://assess.praxicraft.com/assess/settings/integrations?provider=greenhouse",
    },
  },
  {
    resource: "integration",
    operation: "test",
    moduleType: "action",
    label: "Test Integration",
    description: "Test an ATS connector.",
    method: "POST",
    path: "/integrations/{{parameters.provider}}/test/",
    params: [
      { name: "provider", type: "select", label: "ATS Provider", required: true, options: PROVIDER_OPTIONS },
    ],
    sample: { ok: true },
  },
];

module.exports = { CATALOG, camelModule, EVENT_OPTIONS, ASSESS_WEBHOOK_EVENTS };
